#! /bin/bash
chmod +x /action/exec.exe

export PATH=/root/llvm/build/bin:$PATH
export LD_LIBRARY_PATH=/root/llvm/build/lib:$LD_LIBRARY_PATH
SYCL_DEVICE_FILTER=$(jq -r '(.SYCL_DEVICE_FILTER)') 
./exec.exe 

#./exec.exe
#echo "{\"msg\": \"res: $(cat f1)  \" }"
#echo "{\"msg\": \"res: $(printenv PATH)  \" }"
