#!/bin/bash

ACTION_NAME=dpcpp_action
ACTION_SCRIPT=action.sh

#delete existing action
wsk action delete $ACTION_NAME

#create new action with action script as action name
wsk action create $ACTION_NAME $ACTION_SCRIPT --docker openwhisk/dockerskeleton

#invoke the action and print the result
wsk action invoke $ACTION_NAME --result
